sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: QpGdhPzOETNWhlbPjmToGq+VOr9qrnb5uoxjuGoAfD/DtZiRabPolx2pt0tShD98UWfjHwd8ZjTN/RiowoiX97u9GIVjJE+UE/eg7OMU+SNarsou29UrqLrZ0GO6qh5cp7AMdfiJOmdUqlhktm6WToDohbNrsTwwNkRj2VyUuNVJO4/U0eZLBLpwBPT16zrVOMy8MlVQk/KkTb2Ide3wfPca79ZqspFzFOavxLTUuw+DBAEfXY/FRotW3Cnh+Jtq1PYVE0XYQeJR10qEfT0GhM3D+kxcuEgcGgXe7IFXu70buO0lEWALl0MIb+MxKsJI8UFUintLWfVZ3mWdwF1Ue9kYd+wv+T/Gy0h7yDBhUnAB26BujUs60o8sw5ms94WefvrwB/1Fyw0qy/5avDZJ/jmqGzon6AMizEdEyk/bmzZi/XeL5br1EjJD9jSmA2TdQ8yV4RieqwfYf9eQM9VhRTNHQqlVn9U6gKcpQMrxosRAlG51uNhBc8j0SNN2AYrUdJu3bAsvMBb6x7AgwNWnU0ZG6tCN6m6MXOrzoH1VSBQQHDwP0IiINRy4DIESl0UuPv/hxKhHxod1qgM1nKj9W0xoE0ha3xo8aGkGFBaLDwyAsc5f5wktjA5QYHLWihnSTqqQONyFMpbwsXueYHwHiZPXEeZHHfWlXfQX9KdSQXc=
  - secure: MkmW7muNIaQKFaK8sNfL+woqQJA4rBjol3Kg1OE+o87azoKVBpl9bG+iVvyBjw3ikttv+HnlWgmTVTXSY4fiOa44Fu6pVcGOHXp2rLaGyqyy+Thv3mOVUk8CVboyWcrOqNkzzsi8hvLd72L5ptG+G7+q6crbOXPSGsVT1rdn+z1DcSmxs2s4HjWi/6GD/KUUg2+/8if0eoH2W0OgYOXtWaijPlSAylYiQZwOwB2bm4H4Oa21JYjoUuFo4Pkhd6DYCoWQ9z7Yp7ftDODpu+ZsaFUG8IDc1p7iu6P8tLGQ623x+7y72aUw48beXG8rGTRb14aHMd//5DFNTZ7lAj0GCKBMdPwKn+aYEbv9gSA4J6g374hSk7d8kF4ygntnT1hp+u1qU86LuGikl+TAS6Eb7dpMJeQYW3eo04JKJ+gY4BbGHbwWVgX7hdqa1j1LO1BTrR6b4OoyhDr33JLk/Ph5VkyG1IMGXiTc4t775y8krfyDNnBc3/5CUEl82PQ8+NKU3jqRNvRLLdRZM0ZvS9eh4oUUQg/vh26WVlrRS2ddablHV5WvcrKUdtD6MnYNDNef1ucBv244wzcdqoIgWMSVhpdLGSHN2AyrMvELdd9x2vCL+suvMal8SQ+CiIU0JV8jBJXEivZpPXRm7rjrd4Q8jnESrIiN9Wtbs4/ki3sb8XU=
  - secure: UFbg19b7/QFQRBXPdsuSofT3yeMBW7JNjquWpVklPPYsYJoZLt9N7HYIkOhHKbOuZLq3avcCiha3eAcK1aEWfG2zZzt6lNwPEdRW0xpDIpRdw5CEqHzkjLI9AK3L5Jirv55jJaM6UioTVP5uakhBsUcP2RvhCcOegs46lLgItxwYgwxGOMkLk7SRc+1WQdILnyomX3VNaMhsDtmYodrOycyI3Mua+oLv80xqBw0c6KKTzjNCwXZK/xLN1u10GlTUluOrExoCx6FqfFlPm9rJ99iCEPmW/UoE8cOj255XfBhjhUjbPmGRUkhWemIM1zSLiaaDvhFI9GeNKEfh+5NMKQCxngqVaWaTzlTWNnGrzsW8NXr8gP3V5XPWot1NfXDDhh1IxkLAQxvdwMRmPNoz3i0+lf5d7mGRo0AXx2Cn4I8KmQHxGmaIBfHALdcosfnBBUbCNORj97mmxKLd7gSVAQSqQ0VwvgYWV6S4onaN1CtoIj+v/8mJc6jaPQ5yFrOYXpfO6WYglT5u8JVbz3+OJeljfW2iNbJv9OgXwVdagPfJIhBL+OgHxEuRpyOMKf4Lks5Cp11G34rBAwa467KeL/831v/sGZOhFgOjHgN6TlY1dHvkKxrnZKc5wWPxQDdBFzqz+8XsWEijgV3vhifYBxbF5pW0RoK733p8DR03Qx4=
  - secure: IgpRXwL76NMZ4a+qwGLcM7SrKjmvxZ+vRYunsPtGFqHUJQHklhZHDl/x2C+dgEyaskZQChGwzN64RHqI1SS0rmo5BT3nSyJjtLy++vv+Wzg7Qeaq19jivC4hOPLV3qVOQtxYrT+k8pdfHiYAE9j9E41tz2XiE6MSI7vnl/oC3lS7dhIxRSkUJcBXfqo8xoAuXL6r6SF/pINFtrCCzLrr9IHPi5wPR91XpSovNBVdhAMCAA4SD92Q1Gy4j2oIAF3NCvbdOTKYRgAurGogBVcerWlFpYeyvj4jdfgb1GgbHtjx2f7XZfYOYvilxNyNchdAyIEs7RPRx9XlK3ZL1GH3BI7D2/zC/CUHkl+sZqruTAZpNn4hfzL8/98chkZZczIlMdGTgpyz5t3i4xu/XXULjPGdyxagrvjpyvCE4gyGioX7IzN6/KJzY0ezswTSWThN2KDv0ILiWSAaq6DVSbPDibDLK3q1onPY78iAJ76CRJwuMX3KNBkHuD+jpbKVPHSz2xWXkDD2OzyHzZPh/qHzuixmgYiH7UjMFOuRVp1LHqF1tBJu6cO9zn08MTvb1bOn649/ZJf/7ehPej0c9BX2my5RVlZppSL+50+UsudX+M7SwJXqkeVgGSB8atfWtSBRwewr0fsV5RrVK76gk4KKzSx5UqL2GSczPTrNuAzfSng=
